# Generated by Django 4.2.13 on 2024-06-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_location', models.CharField(max_length=50)),
                ('event_time', models.DateTimeField()),
                ('event_date', models.DateField()),
                ('estimated_attendance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Geographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance_to_next_station', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('entry_count', models.IntegerField()),
                ('exit_count', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('day_of_week', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MetroSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.IntegerField()),
                ('station_id', models.IntegerField()),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=10)),
                ('location', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('passenger_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Socioeconomic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=50)),
                ('population_density', models.IntegerField()),
                ('employment_rate', models.FloatField()),
                ('average_income', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('weather_conditions', models.CharField(max_length=20)),
            ],
        ),
    ]
